# Azure Deployment Environments カタログ用 environment.yaml

name: WebApp Environment
description: セキュア＆スケーラブルなWebアプリケーション環境（App Service, SQL, Key Vault, etc.）をBicepでデプロイ
resourceGroup: $(resourceGroupName)
location: $(location)
templatePath: ./main.bicep
parameters:
  envName:
    type: string
    description: 環境名（リソース名のプレフィックス等に利用）
    required: true
  location:
    type: string
    description: デプロイ先リージョン
    required: true
# 必要に応じて追加パラメータを記載

# tagsやoutputsなども必要に応じて追加可能
