# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: WebApp-with-ACR-Environment
version: 1.0.0
summary: Web application environment with ACR integration
description: This environment supports deployment of a web application including Azure App Service, Azure Container Registry (ACR), Azure SQL Database, and Key Vault. Designed for security and scalability.
runner: bicep
templatePath: ./main.bicep
parameters:
  - id: envName
    name: Environment Name
    description: Name prefix for resources in this environment
    type: string
    required: true
