# Checkov Configuration for Bicep Security Scanning

# Framework to scan
framework: 
  - bicep
  - arm

# Directories to scan
directory: 
  - environments/WebApp-ACR-templates/

# Specific checks to run (Azure security checks)
check:
  - CKV_AZURE_1   # Ensure that 'Secure transfer required' is set to 'Enabled'
  - CKV_AZURE_2   # Ensure that storage account access keys are periodically regenerated
  - CKV_AZURE_3   # Ensure that 'Data encryption in transit' is set to 'On' for MySQL Database Server
  - CKV_AZURE_4   # Ensure that 'Enforce SSL connection' is set to 'ENABLED' for MySQL Database Server
  - CKV_AZURE_5   # Ensure that 'Enforce SSL connection' is set to 'ENABLED' for PostgreSQL Database Server
  - CKV_AZURE_9   # Ensure that 'Enable Infrastructure Encryption' for Each Storage Account in Azure Storage is set to 'enabled'
  - CKV_AZURE_11  # Ensure that 'Data encryption in transit' is set to 'On' for PostgreSQL Database Server
  - CKV_AZURE_13  # Ensure App Service Authentication is set up for apps in Azure App Service
  - CKV_AZURE_14  # Ensure web app redirects all HTTP traffic to HTTPS in Azure App Service
  - CKV_AZURE_15  # Ensure that 'HTTP Version' is the latest if used to run the web app
  - CKV_AZURE_16  # Ensure that Register with Azure Active Directory is enabled on App Service
  - CKV_AZURE_17  # Ensure the web app has 'Client Certificates (Incoming client certificates)' set to 'On'
  - CKV_AZURE_18  # Ensure that 'Python version' is the latest, if used to run the web app
  - CKV_AZURE_33  # Ensure Storage logging is enabled for Queue service for read, write and delete requests
  - CKV_AZURE_34  # Ensure that 'Public access level' is disabled for storage accounts with blob containers
  - CKV_AZURE_35  # Ensure default network access rule for Storage Accounts is set to deny
  - CKV_AZURE_36  # Ensure that 'Secure transfer required' is set to 'Enabled'
  - CKV_AZURE_37  # Ensure that 'Data encryption in transit' is set to 'On' for MySQL Database Server
  - CKV_AZURE_40  # Ensure that 'Enforce SSL connection' is set to 'ENABLED' for PostgreSQL Database Server
  - CKV_AZURE_42  # Ensure the key vault is recoverable
  - CKV_AZURE_43  # Ensure Storage Accounts adhere to the naming rules
  - CKV_AZURE_44  # Ensure Storage Account is using the latest version of TLS encryption
  - CKV_AZURE_47  # Ensure that 'Enforce SSL connection' is set to 'ENABLED' for MySQL Database Server
  - CKV_AZURE_48  # Ensure that 'Enforce SSL connection' is set to 'ENABLED' for PostgreSQL Database Server
  - CKV_AZURE_50  # Ensure Storage Account is using the latest version of TLS encryption
  - CKV_AZURE_52  # Ensure Storage Account is using the latest version of TLS encryption
  - CKV_AZURE_59  # Ensure that Storage blobs restrict public access
  - CKV_AZURE_62  # Ensure that App service enables HTTP logging
  - CKV_AZURE_63  # Ensure that App service enables detailed error messages
  - CKV_AZURE_64  # Ensure that App service enables failed request tracing
  - CKV_AZURE_65  # Ensure that App service enables HTTP logging
  - CKV_AZURE_66  # Ensure that App service enables detailed error messages
  - CKV_AZURE_67  # Ensure that 'PHP version' is the latest, if used to run the web app
  - CKV_AZURE_80  # Ensure that 'Net Framework version' is the latest, if used as a part of the web app
  - CKV_AZURE_88  # Ensure that app services use Azure Files
  - CKV_AZURE_89  # Ensure that Managed identity provider is enabled for app services
  - CKV_AZURE_92  # Ensure that App Service is not configured to use basic authentication for FTP deployments
  - CKV_AZURE_95  # Ensure that managed identity provider is enabled for app services
  - CKV_AZURE_109 # Ensure that key vault allows firewall rules settings
  - CKV_AZURE_110 # Ensure that key vault enables purge protection
  - CKV_AZURE_112 # Ensure that key vault enables soft delete
  - CKV_AZURE_113 # Ensure that SQL server disables public network access
  - CKV_AZURE_114 # Ensure that key vault enables firewall rules settings
  - CKV_AZURE_129 # Ensure that Key Vault disallows public network access
  - CKV_AZURE_130 # Ensure that App service enables detailed error messages
  - CKV_AZURE_133 # Ensure that Cognitive Services accounts disable public network access
  - CKV_AZURE_148 # Ensure that Virtual Machines use managed disks
  - CKV_AZURE_149 # Ensure that Virtual Machine scale sets have managed disk data encryption set
  - CKV_AZURE_150 # Ensure that Virtual Machine scale sets use managed disks for OS disks
  - CKV_AZURE_151 # Ensure Windows VM enables encryption
  - CKV_AZURE_169 # Ensure SQL server is using latest TLS/SSL version
  - CKV_AZURE_170 # Ensure web app is using latest TLS/SSL version

# Checks to skip (if any specific checks need to be excluded)
skip-check: []

# Output format
output: sarif

# Severity levels to include
severity: 
  - CRITICAL
  - HIGH  
  - MEDIUM
  - LOW

# Enable verbose output
verbose: true

# Include source code in output
include-all-checkov-policies: true

# Compact mode (reduces output size)
compact: false

# Enable secrets scanning
enable-secrets-scan-all-files: true

# External checks directory (if you have custom checks)
external-checks-dir: []

# Frameworks to exclude
skip-framework: []

# File types to include
file-types:
  - bicep
  - json

# Baseline file for comparing results
# baseline: checkov-baseline.json